# Generated by Django 2.2.2 on 2019-08-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhr', '0002_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dni',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
